# Generated by Django 3.1.1 on 2020-10-05 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20201005_1611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='user_address',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
