# Generated by Django 3.1.1 on 2020-10-05 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20201005_1629'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
